services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: badiro12
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: main-dev-bsn
    image:  maildev/maildev
    ports:
      - 1080:1080
      - 1075:1075


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
